---
- hosts: local

  vars_files:
    - default.config.yml

  pre_tasks:
    # Allow default configuration to be overridden.
    - include_vars: "{{ item }}"
      with_fileglob:
        - "config.yml"
      tags: ['always']

    - name: Enable Backports repository.
      apt_repository:
        repo: 'deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main'
        state: present
        filename: "{{ ansible_distribution_release }}_backports"
      register: debian_backports

    - name: Update apt cache.
      apt: update_cache=yes
      when: debian_backports.changed

    # See: http://unix.stackexchange.com/a/342469
    - name: Install dependencies.
      apt:
        default_release: "{{ ansible_distribution_release }}-backports"
        name:
          - openjdk-8-jre-headless
          - ca-certificates-java
        state: present

  roles:
    - geerlingguy.java
    - geerlingguy.solr
